# Generated by Django 4.2.4 on 2023-10-16 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRJ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sheet_no', models.CharField(blank=True, max_length=100, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_crj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReceiptsJournal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rcd', models.CharField(blank=True, max_length=100, null=True)),
                ('jev_no', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_collecting_officer', models.CharField(blank=True, max_length=255, null=True)),
                ('col_debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('col_debit_uacs_object_code', models.CharField(blank=True, max_length=255, null=True)),
                ('col_credit_or_no', models.CharField(blank=True, max_length=100, null=True)),
                ('col_credit_transaction', models.CharField(blank=True, max_length=255, null=True)),
                ('col_credit_payor', models.CharField(blank=True, max_length=255, null=True)),
                ('col_credit_uacs_name', models.CharField(blank=True, max_length=255, null=True)),
                ('col_credit_sundry_uacs_object_code', models.CharField(blank=True, max_length=255, null=True)),
                ('col_credit_sundry_p', models.CharField(blank=True, max_length=100, null=True)),
                ('col_credit_sundry_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dep_debit_deposited_account', models.CharField(blank=True, max_length=255, null=True)),
                ('dep_date_of_deposit', models.DateField(blank=True, null=True)),
                ('dep_debit_sundry_uacs_object_code', models.CharField(blank=True, max_length=255, null=True)),
                ('dep_debit_sundry_p', models.CharField(blank=True, max_length=100, null=True)),
                ('dep_debit_sundry_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dep_credit_uacs_object_code', models.CharField(blank=True, max_length=255, null=True)),
                ('dep_credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('crj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts_journal.crj')),
            ],
            options={
                'db_table': 'tbl_receipts_journal',
                'managed': True,
            },
        ),
    ]
