# Generated by Django 4.2.4 on 2023-10-17 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsjournal',
            name='crj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='receipts_journal.crj'),
        ),
    ]
