# Generated by Django 4.2.4 on 2023-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_journal', '0005_alter_receiptsjournal_col_credit_sundry_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptsjournal',
            name='col_credit_sundry_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='receiptsjournal',
            name='col_debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='receiptsjournal',
            name='dep_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='receiptsjournal',
            name='dep_debit_sundry_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
    ]
