# Generated by Django 4.2.4 on 2023-10-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts_journal', '0006_alter_receiptsjournal_col_credit_sundry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crj',
            name='remarks',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
