# Generated by Django 4.2.4 on 2023-09-29 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementJournal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recon_no', models.IntegerField(blank=True, null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('check_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dv_year', models.CharField(blank=True, max_length=100, null=True)),
                ('dv_month', models.CharField(blank=True, max_length=100, null=True)),
                ('dv_no', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('payee', models.TextField(blank=True, max_length=100, null=True)),
                ('nature_of_payment', models.TextField(blank=True, max_length=100, null=True)),
                ('check_tmp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax2_percent', models.CharField(blank=True, max_length=100, null=True)),
                ('remittance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rod', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_position', models.CharField(blank=True, max_length=255, null=True)),
                ('ppa', models.CharField(blank=True, max_length=100, null=True)),
                ('charge_center', models.CharField(blank=True, max_length=100, null=True)),
                ('set', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('fund', models.CharField(blank=True, max_length=100, null=True)),
                ('account_code', models.CharField(blank=True, max_length=100, null=True)),
                ('old_code', models.CharField(blank=True, max_length=100, null=True)),
                ('alobs_year', models.CharField(blank=True, max_length=100, null=True)),
                ('alobs_month', models.CharField(blank=True, max_length=100, null=True)),
                ('alobs_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sa_aamt', models.CharField(blank=True, max_length=100, null=True)),
                ('earmark', models.CharField(blank=True, max_length=100, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ap_charge_from', models.CharField(blank=True, max_length=100, null=True)),
                ('old_code2', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_remarks', models.TextField(blank=True, max_length=100, null=True)),
                ('budget_code', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_class', models.CharField(blank=True, max_length=100, null=True)),
                ('authorization', models.CharField(blank=True, max_length=255, null=True)),
                ('bur_ap', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('quarter', models.CharField(blank=True, max_length=255, null=True)),
                ('saa_no', models.CharField(blank=True, max_length=100, null=True)),
                ('rao_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('uacs_description', models.CharField(blank=True, max_length=255, null=True)),
                ('cmf_dr', models.CharField(blank=True, max_length=100, null=True)),
                ('bur', models.CharField(blank=True, max_length=100, null=True)),
                ('aa', models.CharField(blank=True, max_length=100, null=True)),
                ('dd_nyd', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_disbursement_journal',
                'managed': True,
            },
        ),
    ]
