# Generated by Django 4.2.4 on 2023-09-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementjournal',
            name='tax_percent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
