# Generated by Django 4.2.4 on 2023-09-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement_journal', '0002_disbursementjournal_tax_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementjournal',
            name='author',
        ),
    ]
