# Generated by Django 4.2.4 on 2023-09-29 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disbursement_journal', '0003_remove_disbursementjournal_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDJ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_cdj',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='disbursementjournal',
            name='cdj_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='disbursement_journal.cdj'),
        ),
    ]
