# Generated by Django 4.2.4 on 2023-10-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disbursement_journal', '0005_remove_disbursementjournal_tax_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementjournal',
            name='cdj_id',
        ),
        migrations.AddField(
            model_name='disbursementjournal',
            name='cdj',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='disbursement_journal.cdj'),
        ),
    ]
