# Generated by Django 4.2.4 on 2023-09-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uacs_object_code', models.CharField(blank=True, max_length=100, null=True)),
                ('account_title', models.TextField(blank=True, null=True)),
                ('rca_code', models.CharField(blank=True, max_length=100, null=True)),
                ('uacs_subject_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lib_accounts',
                'managed': True,
            },
        ),
    ]
