# Generated by Django 4.2.4 on 2023-09-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_accounts_created_at_accounts_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='uacs_subject_code',
            new_name='uacs_subobject_code',
        ),
    ]
