# Generated by Django 4.2.4 on 2023-09-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_rename_uacs_subject_code_accounts_uacs_subobject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_title',
            field=models.TextField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='rca_code',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='uacs_object_code',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
