# Generated by Django 4.2.4 on 2023-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_alter_accounts_account_title_alter_accounts_rca_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='accounts',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
