# Generated by Django 4.2.4 on 2023-10-31 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sheet', models.TextField(blank=True, max_length=255, null=True)),
                ('month', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_journal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeneralJournal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('jev_no', models.CharField(blank=True, max_length=100, null=True)),
                ('particulars', models.TextField(blank=True, max_length=100, null=True)),
                ('uacs_object_code', models.CharField(blank=True, max_length=100, null=True)),
                ('p', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_debit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_journal.journal')),
            ],
            options={
                'db_table': 'tbl_general_journal',
                'managed': True,
            },
        ),
    ]
