# Generated by Django 4.2.4 on 2023-10-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='sheet',
            new_name='sheet_no',
        ),
    ]
