# Generated by Django 4.2.4 on 2023-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_journal', '0002_rename_sheet_journal_sheet_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaljournal',
            name='p',
            field=models.BooleanField(default=False),
        ),
    ]
